# Use an official Ubuntu base image
FROM ubuntu:latest

# Set environment variables for non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Update package list and install Graphviz and necessary dependencies
RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-pip \
    python3-venv \
    graphviz \
    xdot \
    x11-apps \
    dbus-x11 \
    at-spi2-core \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a virtual environment and activate it
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip and install setuptools
RUN pip3 install --upgrade pip setuptools


# ##USER: OPTION 1
# #
# # Add a user for running the application
# RUN useradd -ms /bin/bash graphviz_user
# # Switch to the new user
# USER graphviz_user
# WORKDIR /home/graphviz_user
# #
# # Set the entrypoint to bash
# ENTRYPOINT ["bash"]
# # ENTRYPOINT ["tail", "-f", "/dev/null"]


#USER: OPTION 2

ARG UNAME=graphviz_user
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

USER $UNAME
